### ISSUE TITLE
ddtrace-run error in compilation

### ISSUE THREAD

**Issue by romayankin** [DataDog/hiring-engineers#365]
Do you happen to know what's causing this error (OS Win 10)

d:\temp>ddtrace-run app.py
Traceback (most recent call last):
  File "C:\Users\ryankin\AppData\Local\Programs\Python\Python36\Scripts\ddtrace-run-script.py", line 11, in <module>
    load_entry_point('ddtrace==0.11.1', 'console_scripts', 'ddtrace-run')()
  File "c:\users\ryankin\appdata\local\programs\python\python36\lib\site-packages\ddtrace\commands\ddtrace_run.py", line 78, in main
    os.execl(executable, executable, *sys.argv[2:])
  File "c:\users\ryankin\appdata\local\programs\python\python36\lib\os.py", line 527, in execl
    execv(file, args)
TypeError: execv: path should be string, bytes or os.PathLike, not NoneType

It appears everytime no matter what code I'm running.

I've tried both running CMD with Administrator privilege and without to no avail.

**Comment by romayankin** [comment]
So what's the answer?

**Comment by LeeFreer** [comment]
Hi there - we're unable to tell which recruiting candidate you are from your user profile. Please reach out to your recruiter contact and/or hiring manager contact for details. Thank you!
